version: '3.5'
services:

  ipinfo_backend:
    container_name: scso-backend
    restart: always
    volumes:
      - logs:/logs
    ports:
      - 5001:5001
    env_file:
      - ../.env
    healthcheck:
       test: curl -sS http://0.0.0.0:5001/swaggerui/ || echo 1
       interval: 1m30s
       timeout: 10s
       retries: 3
    depends_on:
      - ipinfo_db
    networks:
      - ipinfo-network
  
  ipinfo_db:
    container_name: ipinfo-db
    restart: always
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    networks:
      - ipinfo-network
      
volumes:
  logs:
  uploads:
  postgresql_data:
networks:
  ipinfo-network:
    name: ipinfo-network